/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Utilizador
 */
public class area_empregado extends javax.swing.JFrame {

int empregado=0;
int bar =0;
String cat="";
    public area_empregado() {
        initComponents();
    }

 
    public area_empregado(int id_empregado,int id_bar, String categoria) {
        initComponents();
        empregado=id_empregado;
        bar=id_bar;
        cat=categoria;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_armazem = new javax.swing.JButton();
        butao_pedidos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        botao_faturas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botao_armazem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_armazem.setText("Armazém");
        botao_armazem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_armazemActionPerformed(evt);
            }
        });

        butao_pedidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butao_pedidos.setText("Tratar Pedidos");
        butao_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao_pedidosActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        botao_faturas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_faturas.setText("Faturas");
        botao_faturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_faturasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(botao_armazem, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(butao_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(botao_faturas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butao_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_armazem, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_faturas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        new Inicio().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void butao_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao_pedidosActionPerformed
        if(cat.contains("balcao")){
            new finalizar_pedido(bar).setVisible(true);
            
        }else{
             JOptionPane.showMessageDialog(null, "Só o empregado encarregue do balcão pode finalizar os pedidos!! ");
        
        }
            
    }//GEN-LAST:event_butao_pedidosActionPerformed

    private void botao_faturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_faturasActionPerformed
             if(cat.contains("chefe_bar")){
            new faturas(bar).setVisible(true);
            
        }else{
             JOptionPane.showMessageDialog(null, "Só os chefes dos bares  podem ver as faturas!! ");
        
        }
    }//GEN-LAST:event_botao_faturasActionPerformed

    private void botao_armazemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_armazemActionPerformed
                if(cat.contains("armazem")){
                    setVisible(false);
            new escolher_bar_armazem(empregado,bar,cat).setVisible(true);
            
        }else{
             JOptionPane.showMessageDialog(null, "Só o responsavel do armazém pode aceder ao armazem!! ");
        
        }
    }//GEN-LAST:event_botao_armazemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(area_empregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(area_empregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(area_empregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(area_empregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new area_empregado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_armazem;
    private javax.swing.JButton botao_faturas;
    private javax.swing.JButton butao_pedidos;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
