/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Utilizador
 */
public class criar_pedido extends javax.swing.JFrame {

    /**
     * Creates new form criar_pedido
     */
    int numero=0;
    int bar=0;
    int mesa_int=0;
            
    public criar_pedido() {
        initComponents();
    }
     public criar_pedido(int id_mesa,int numero_pessoas,int id_bar) {
        initComponents();
        String mesa=String.valueOf(id_mesa);
        mesa_label.setText(mesa);
        numero=numero_pessoas;
        bar=id_bar;
        mesa_int=id_mesa;
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butao_pedido = new javax.swing.JButton();
        butao_sair = new javax.swing.JButton();
        mesa_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butao_pedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        butao_pedido.setText("Fazer Pedido");
        butao_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao_pedidoActionPerformed(evt);
            }
        });

        butao_sair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        butao_sair.setText("Sair da mesa");
        butao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao_sairActionPerformed(evt);
            }
        });

        mesa_label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Id mesa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mesa_label, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1142, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butao_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229)
                .addComponent(butao_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(393, 393, 393))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mesa_label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 574, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butao_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butao_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao_sairActionPerformed
         try{
        Connection con = ConnectionProvider.Connector();
        String insert="update mesa  set lotacao_atual= lotacao_atual - ? where id_mesa= ? and id_bar=? ";
         PreparedStatement pst=con.prepareStatement(insert);
         pst.setInt(1, numero);
         pst.setInt(2,mesa_int);
         pst.setInt(3,bar);
         pst.executeUpdate();
        
        setVisible(false);
        new Inicio().setVisible(true);
         }catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
         }
        
    }//GEN-LAST:event_butao_sairActionPerformed

    private void butao_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao_pedidoActionPerformed
        try {
            Connection con = ConnectionProvider.Connector();
            String mesa=mesa_label.getText();
            int id_mesa=Integer.parseInt(mesa);
            String estado="aberto";
            String insert="INSERT INTO pedido(data,estado,id_mesa) values(date('now'),?,?)";
            PreparedStatement pst=con.prepareStatement(insert);
            pst.setString(1, estado);
            pst.setInt(2,id_mesa);
            pst.executeUpdate();
            String query ="SELECT id_pedido from pedido order by id_pedido desc Limit 1";
            Statement st= con.createStatement();
           ResultSet rs=st.executeQuery(query);
        
           int id_pedido=0;
        while(rs.next()){
            id_pedido=rs.getInt("id_pedido");
        }
            new  adicionar_pedido(id_pedido).setVisible(true);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_butao_pedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(criar_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(criar_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(criar_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(criar_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new criar_pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butao_pedido;
    private javax.swing.JButton butao_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mesa_label;
    // End of variables declaration//GEN-END:variables
}
