/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Utilizador
 */
public class escolher_mesa extends javax.swing.JFrame {

    /**
     * Creates new form escolher_mesa
     */
    int id_bar_passar=0;
    public escolher_mesa() {
        initComponents();
    }
      public escolher_mesa(int id_bar) {
        initComponents();
        mostrar_mesa(id_bar);
        fill_Combo(id_bar);
        id_bar_passar=id_bar;
        
    }
      
        public ArrayList <mesa> mesa_info(int id_bar) {//armazenar info da tabela bar
         ArrayList <mesa> mesa_info = new ArrayList<>();
         try{
        Connection con = ConnectionProvider.Connector();
        String query ="SELECT * FROM mesa WHERE id_bar=?";
        PreparedStatement pst= con.prepareStatement(query);
        pst.setInt(1,id_bar);
        ResultSet rs=pst.executeQuery();
        
        mesa m;
        while(rs.next()){
            m=new mesa(rs.getInt("id_mesa"),rs.getInt("lotacao_max"),rs.getInt("lotacao_atual"),rs.getInt("id_bar"));
            mesa_info.add(m);
        }
        
        
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
         return mesa_info;
    }
        public void mostrar_mesa(int id_bar){//distribuir info da tabela mesa na jtable
        ArrayList<mesa> lista =mesa_info(id_bar);
        DefaultTableModel model =(DefaultTableModel)tabela_mesa.getModel();
        Object[]  row= new Object [4];
        for (int i = 0; i < lista.size(); i++) {
            row[0]=lista.get(i).getId_mesa();
            row[1]=lista.get(i).getLotacao_max();
            row[2]=lista.get(i).getLotacao_atual();
            row[3]=lista.get(i).getId_bar();
            model.addRow(row);
            
        }
        }
            public void fill_Combo(int id_bar){
        try{
            Connection con = ConnectionProvider.Connector();
            String query ="SELECT id_mesa FROM mesa WHERE id_bar=?";
            PreparedStatement pst= con.prepareStatement(query);
            pst.setInt(1,id_bar);
            ResultSet rs=pst.executeQuery();
                  while(rs.next()){
                    String s =String.valueOf(rs.getInt("id_mesa"));
                    escolher_mesa_comboBox.addItem(s);
        }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escolher_mesa_comboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_mesa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        numero_pessoas_comboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela_mesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_mesa", "lotacao_max", "lotacao_atual"
            }
        ));
        jScrollPane1.setViewportView(tabela_mesa);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Escolher mesa:");

        jButton1.setText("Sentar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Numero de pessoas a sentar:");

        numero_pessoas_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(escolher_mesa_comboBox, 0, 97, Short.MAX_VALUE)
                            .addComponent(numero_pessoas_comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(61, 61, 61)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(escolher_mesa_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero_pessoas_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        new Inicio().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String id_mesa_temp ;
            int lotacao_atual=0; 
            int lotacao_max=0; 
            String numero_pessoas;
            Connection con = ConnectionProvider.Connector();
             String query ="SELECT lotacao_max FROM mesa WHERE id_mesa=?";
             id_mesa_temp = escolher_mesa_comboBox.getSelectedItem().toString();
             int id_mesa=Integer.parseInt(id_mesa_temp);
             PreparedStatement pst= con.prepareStatement(query);
             pst.setInt(1,id_mesa);
             ResultSet rs=pst.executeQuery();
             while(rs.next()){
                 lotacao_max=rs.getInt("lotacao_max");
             }
              String query1 ="SELECT lotacao_atual FROM mesa WHERE id_mesa = ? ";
             PreparedStatement pst1= con.prepareStatement(query1);
             pst1.setInt(1,id_mesa);
             ResultSet rs1=pst1.executeQuery();
             while(rs1.next()){
                 lotacao_atual=rs1.getInt("lotacao_atual");
             }
             numero_pessoas= numero_pessoas_comboBox.getSelectedItem().toString();
             int numero=Integer.parseInt(numero_pessoas);
             if(lotacao_max>=lotacao_atual+numero){
              
                String query2 ="UPDATE mesa SET lotacao_atual= ?  WHERE id_mesa= ?";
                PreparedStatement pst2= con.prepareStatement(query2);
                pst2.setInt(1,(lotacao_atual+numero));
                pst2.setInt(2,id_mesa);
                pst2.executeUpdate();
                 setVisible(false);
                 new criar_pedido(id_mesa,numero,id_bar_passar).setVisible(true);
                 
             }else{
                 JOptionPane.showMessageDialog(null, "Gente a mais!!");
             }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(escolher_mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(escolher_mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(escolher_mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(escolher_mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new escolher_mesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> escolher_mesa_comboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> numero_pessoas_comboBox;
    private javax.swing.JTable tabela_mesa;
    // End of variables declaration//GEN-END:variables
}
