/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Utilizador
 */
public class escolher_bar_armazem extends javax.swing.JFrame {
 int bar_escolhido=0;
 int empregado=0;
 int bar=0;
 String cat="";
    public escolher_bar_armazem() {
        initComponents();
    }
        public escolher_bar_armazem(int id_empregado,int id_bar, String categoria) {
            initComponents();
            empregado=id_empregado;
            bar=id_bar;
            cat=categoria;
            mostrar_bar();
            fill_Combo();
    }

    
     public ArrayList <bar> bar_info() {//armazenar info da tabela bar
         ArrayList <bar> bar_info= new ArrayList<>();
         try{
        Connection con = ConnectionProvider.Connector();
        String query ="SELECT * FROM bar";
        Statement st= con.createStatement();
        ResultSet rs=st.executeQuery(query);
        
        bar b;
        while(rs.next()){
            b=new bar(rs.getInt("id_bar"),rs.getString("distrito"),rs.getString("localidade"),rs.getString("pais"),rs.getString("codigo_postal"));
            bar_info.add(b);
        }
        
        
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
         return bar_info;
    }
    public void mostrar_bar(){//distribuir info da tabela bar na jtable
        ArrayList<bar> lista=bar_info();
        DefaultTableModel model =(DefaultTableModel)tabela_bar.getModel();
        Object[]  row= new Object [5];
        for (int i = 0; i < lista.size(); i++) {
            row[0]=lista.get(i).getId_bar();
            row[1]=lista.get(i).getDistrito();
            row[2]=lista.get(i).getLocalidade();
            row[3]=lista.get(i).getPais();
            row[4]=lista.get(i).getCodigo_postal();
            model.addRow(row);
            
        }
        
    /**
     *
     */

    
    }
    public void fill_Combo(){
        try{
            Connection con = ConnectionProvider.Connector();
            String query ="SELECT id_bar FROM bar";
            Statement st= con.createStatement();
            ResultSet rs=st.executeQuery(query);
                  while(rs.next()){
                    String s =String.valueOf(rs.getInt("id_bar"));
                    escolher_bar_comboBox.addItem(s);
        }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        escolher_bar_comboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_bar = new javax.swing.JTable();
        botao_escolher = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel1.setText("Escolher bar id:");

        tabela_bar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_bar", "distrito", "localidade", "país", "codigo-postal"
            }
        ));
        jScrollPane1.setViewportView(tabela_bar);

        botao_escolher.setText("Escolher");
        botao_escolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_escolherActionPerformed(evt);
            }
        });

        botao_sair.setText("Voltar");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(escolher_bar_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botao_escolher, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botao_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(escolher_bar_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_escolher, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_escolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_escolherActionPerformed
        String selecionado = escolher_bar_comboBox.getSelectedItem().toString();
       bar_escolhido=Integer.parseInt(selecionado);
        setVisible(false);
        new area_armazem(bar_escolhido,bar,empregado,cat).setVisible(true);
        

    }//GEN-LAST:event_botao_escolherActionPerformed

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        setVisible(false);
        new  area_empregado (empregado,bar,cat).setVisible(true);
    }//GEN-LAST:event_botao_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(escolher_bar_armazem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(escolher_bar_armazem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(escolher_bar_armazem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(escolher_bar_armazem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new escolher_bar_armazem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_escolher;
    private javax.swing.JButton botao_sair;
    private javax.swing.JComboBox<String> escolher_bar_comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_bar;
    // End of variables declaration//GEN-END:variables
}
