/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Utilizador
 */
public class finalizar_pedido extends javax.swing.JFrame {

    /**
     * Creates new form finalizar_pedido
     */
    int id_bar=0;
    public finalizar_pedido() {
        initComponents();
    }
        public finalizar_pedido(int bar) {
        initComponents();
        id_bar=bar;
        mostrar_pedido_aberto(id_bar);
        fill_Combo( id_bar);
        
    }   public ArrayList <pedido_final> pedido_final_info(int id_bar) {
         ArrayList <pedido_final> pedido_final_lista = new ArrayList<>();
         try{
        Connection con = ConnectionProvider.Connector();
        String query ="SELECT pedido.id_pedido, data, estado  FROM pedido_info inner join pedido on pedido.id_pedido=pedido_info.id_pedido where id_bar=? and estado = 'aberto'  GROUP BY pedido_info.id_pedido";
        PreparedStatement pst= con.prepareStatement(query);
        pst.setInt(1,id_bar);
        ResultSet rs=pst.executeQuery();
        
        pedido_final pf;
        while(rs.next()){
            pf=new pedido_final(rs.getInt("id_pedido"),rs.getString("data"),rs.getString("estado"));
            pedido_final_lista.add(pf);
        }
        
     pst.close();
     rs.close();
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
            return pedido_final_lista;
    }
      
    
    
  
    public  void mostrar_pedido_aberto(int id_bar){
        ArrayList<pedido_final> lista = pedido_final_info(id_bar);
        DefaultTableModel model =(DefaultTableModel)pedido_final_tabela.getModel();
        Object[]  row= new Object [3];
        for (int i = 0; i < lista.size(); i++) {
            row[0]=lista.get(i).getId_pedido();
            row[1]=lista.get(i).getData();
            row[2]=lista.get(i).getEstado();
            model.addRow(row);
            
        }
        }
    public void fill_Combo(int id_bar){
        try{
            Connection con = ConnectionProvider.Connector();
            String query ="SELECT id_pedido FROM pedido_info WHERE id_bar=? GROUP BY id_pedido";
            PreparedStatement pst= con.prepareStatement(query);
            pst.setInt(1,id_bar);
            ResultSet rs=pst.executeQuery();
                  while(rs.next()){
                    String s =String.valueOf(rs.getInt("id_pedido"));
                    pedido_comboBox.addItem(s);
        }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        pedido_final_tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        pedido_comboBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pedido_final_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_pedido", "data", "estado"
            }
        ));
        jScrollPane2.setViewportView(pedido_final_tabela);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Finalizar pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pedido_comboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pedido_comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pedido_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
              String id_pedido_temp = pedido_comboBox.getSelectedItem().toString();
              int id_pedido=Integer.parseInt(id_pedido_temp);
             
        Connection con = ConnectionProvider.Connector();
        String query ="Select Sum(pedido_info.qtd * produto.preco) as total from pedido_info inner join produto on pedido_info.id_produto=produto.id_produto where id_pedido=?";
        PreparedStatement pst= con.prepareStatement(query);
        pst.setInt(1,id_pedido);
        ResultSet rs=pst.executeQuery();
        
       double preco_total=rs.getDouble("total");
        
       
        pst.close();
        rs.close();
        
     String insert ="insert into fatura(preco,data,id_bar) values(?, date('now'), ?)";
                  PreparedStatement pst2= con.prepareStatement(insert);
                  pst2.setDouble(1,preco_total);
                  pst2.setInt(2,id_bar);
                  pst2.executeUpdate();
                  
                  pst2.close();
                  
                  String delete ="delete from pedido where id_pedido=?";
                  PreparedStatement pst3= con.prepareStatement(delete);
                  pst3.setInt(1,id_pedido);
                  pst3.executeUpdate();
                  pst3.close();

                  
                   String delete1 ="delete from pedido_info where id_pedido=?";
                  PreparedStatement pst4= con.prepareStatement(delete1);
                  pst4.setInt(1,id_pedido);
                  pst4.executeUpdate();
                  pst4.close();
                  
                          DefaultTableModel dm1 = (DefaultTableModel)pedido_final_tabela.getModel();
                  while(dm1.getRowCount() > 0)
                        {
                            dm1.removeRow(0);
                        }
                 mostrar_pedido_aberto(id_bar);
                 
                 pedido_comboBox.removeAllItems();
                 fill_Combo( id_bar);
                 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finalizar_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finalizar_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finalizar_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finalizar_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finalizar_pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> pedido_comboBox;
    private javax.swing.JTable pedido_final_tabela;
    // End of variables declaration//GEN-END:variables
}
