/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Utilizador
 */
public class transacoes extends javax.swing.JFrame {

    /**
     * Creates new form transacoes
     */
    double despesas=0;
    String despesasS="";
    int id_bar=0;
    public transacoes() {
        initComponents();
    }
        public transacoes(int a) {
            id_bar=0;
            
        initComponents();
        mostrar_transacao_info(id_bar);
    }

        
         public ArrayList <transacao> transacao_info(int id_bar) {
         ArrayList <transacao>transacao_info = new ArrayList<>();
         try{
        Connection con = ConnectionProvider.Connector();
        String query ="SELECT info_stock.id_produto as id_produto,nome as nome,data, tempo,qtd from info_stock inner join produto on info_stock.id_produto=produto.id_produto where id_bar=? ";
        PreparedStatement pst= con.prepareStatement(query);
        pst.setInt(1,id_bar);
        ResultSet rs=pst.executeQuery();
         
        
      transacao t;
        while(rs.next()){
            t=new transacao(rs.getInt("id_produto"),rs.getString("nome"),rs.getString("data"),rs.getString("tempo"),rs.getInt("qtd"));
           transacao_info.add(t);
        }
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
         return transacao_info;
    }
         
         public void mostrar_transacao_info(int id_bar){//distribuir info da tabela mesa na jtable
        ArrayList<transacao> lista =transacao_info(id_bar);
        DefaultTableModel model =(DefaultTableModel)transacoes_tabela.getModel();
        Object[]  row= new Object [5];
        for (int i = 0; i < lista.size(); i++) {
            row[0]=lista.get(i).getId();
            row[1]=lista.get(i).getNome();
            row[2]=lista.get(i).getData();
            row[3]=lista.get(i).getTempo();
            row[4]=lista.get(i).getQtd();
            model.addRow(row);
            
        }
            }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ver_faturas_butao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lucro_total_label = new javax.swing.JLabel();
        botao_sair = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transacoes_tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ver_faturas_butao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ver_faturas_butao.setText("Ver despesas");
        ver_faturas_butao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_faturas_butaoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Despesa total:");

        lucro_total_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        botao_sair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_sair.setText("Sair");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Data:");

        jLabel2.setText("(ano-mes-data)ex:2020-12-27");

        transacoes_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_produto", "nome", "data", "hora", "qtd"
            }
        ));
        jScrollPane1.setViewportView(transacoes_tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lucro_total_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ver_faturas_butao, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botao_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lucro_total_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ver_faturas_butao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ver_faturas_butaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_faturas_butaoActionPerformed
        try{

            String data = jTextField1.getText();
            if(data.equalsIgnoreCase("")){

                DefaultTableModel dm1 = (DefaultTableModel)transacoes_tabela.getModel();
                while(dm1.getRowCount() > 0)
                {
                    dm1.removeRow(0);
                }
                mostrar_transacao_info(id_bar);
                
                Connection con = ConnectionProvider.Connector();
                String query1 ="select sum(preco) as preco from info_stock inner join produto on info_stock.id_produto=produto.id_produto where id_bar=?";
                PreparedStatement pst1= con.prepareStatement(query1);
                pst1.setInt(1,id_bar);
                ResultSet rs1=pst1.executeQuery();
                while(rs1.next()){
                    despesas=rs1.getDouble("preco");
                }
                despesasS=Double.toString(despesas);
                lucro_total_label.setText(despesasS+"€");
                con.close();
                pst1.close();

            }else{

                DefaultTableModel dm2 = (DefaultTableModel)transacoes_tabela.getModel();
                while(dm2.getRowCount() > 0)
                {
                    dm2.removeRow(0);
                }
                 mostrar_transacao_info(id_bar);
                Connection con2 = ConnectionProvider.Connector();
                String query2 ="select sum(preco) as preco from   info_stock inner join produto on info_stock.id_produto=produto.id_produto  where id_bar=? and data=?";
                PreparedStatement pst2= con2.prepareStatement(query2);
                pst2.setInt(1,id_bar);
                pst2.setString(2,data);
                ResultSet rs2=pst2.executeQuery();
                while(rs2.next()){
                    despesas=rs2.getDouble("preco");
                }
                despesasS=Double.toString(despesas);
                lucro_total_label.setText(despesasS+"€");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_ver_faturas_butaoActionPerformed

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        setVisible(false);
    }//GEN-LAST:event_botao_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lucro_total_label;
    private javax.swing.JTable transacoes_tabela;
    private javax.swing.JButton ver_faturas_butao;
    // End of variables declaration//GEN-END:variables
}
